# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Switch branch # https://stackoverflow.com/questions/26961371/switch-on-another-branch-create-if-not-exists-without-checking-if-already-exi
        run: |
          git checkout -B github-pages
          git merge master
      - name: Make dist
        run: |
          md -Force dist

      - name: Restore tools
        run: dotnet tool restore
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      #- name: Test
      #  run: dotnet test --no-build --verbosity normal
      - name: Npm Restore
        run: npm install

      - name: Publish
        run: npm run build

      - uses: actions/upload-artifact@v3
        with:
          name: js
          path: |
            public/bundle.js
            public/index.html
      - name:
          Copy to dist
          # IF exist dist ( echo dist exists ) ELSE ( mkdir dist && echo dist created)
        run: |
          copy public/bundle.js dist/bundle.js
          copy public/index.html dist/index.html
      # - name: Commit changes
      #   run: |
      #     git add --force public/bundle.js
      #     git add public/index.html
      #     git commit -m "${{github.event.head_commit.message}}"
      # - name: CreateBranch
      # https://stackoverflow.com/questions/63619329/github-action-get-commit-message
      # run: |
      #   git checkout -B pages-pr
      #   git add *
      #   git commit -m "${{github.event.head_commit.message}}"
      - name: Create Pull Request
        # https://github.com/peter-evans/create-pull-request/tree/main
        uses: peter-evans/create-pull-request@v5
        with:
          add-paths: |
            dist/bundle.js
            dist/index.html
          branch: pages-update
